version: '2'
services:
  hexo-blog:
    image: "hexo-blog-nginx:1.0"
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 127.0.0.1:4000:80
    restart: always
    networks:
      - hexo
networks:
  hexo:
    ipam:
      driver: default
      config:
        - subnet: 172.16.2.0/24
